name: Build and deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20] # Updated to a more recent LTS version
        go: ['1.22'] # Updated to a more recent Go version
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - name: Install dependencies and build web app
      run: |
        cp spa-github-pages/index.html public/index.html
        yarn install
        export NODE_OPTIONS=--openssl-legacy-provider
        yarn run build
        cp spa-github-pages/404.html build/

    - name: Upload web app build artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-build-gh-pages
        path: build/

    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Generate TeX file for resume
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        yarn run build:resume-json
        cd resume
        go run main.go

    - name: Upload TeX resume artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-tex-ubuntu
        path: ./resume/resume/

  build-macos:
    strategy:
      matrix:
        os: [macos-latest]
        node-version: [20] # Updated to a more recent LTS version
        go: ['1.22'] # Updated to a more recent Go version
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - name: Install dependencies and build web app
      run: |
        yarn install
        export NODE_OPTIONS=--openssl-legacy-provider
        yarn run build

    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Generate TeX file for resume
      run: |
        export NODE_OPTIONS=--openssl-legacy-provider
        yarn run build:resume-json
        cd resume
        go run main.go

    - name: Upload TeX resume artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-tex-macos
        path: ./resume/resume/
      
  build-resume-linux:
    needs: [build-linux]
    runs-on: ubuntu-latest
    steps:
    - name: Download TeX files
      uses: actions/download-artifact@v4
      with:
        name: resume-tex-ubuntu
    - name: Compile TeX to PDF
      uses: xu-cheng/latex-action@v3
      with:
        root_file: ./resume.tex
        latexmk_use_xelatex: true
    - name: Upload resume PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-ubuntu
        path: ./resume.pdf

  build-resume-macos:
    needs: [build-macos]
    runs-on: macos-latest
    steps:
    - name: Download TeX files
      uses: actions/download-artifact@v4
      with:
        name: resume-tex-macos
    - name: Build TeX files
      run: |
        brew install --cask mactex-no-gui
        xelatex resume.tex
    - name: Upload resume PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: resume-macos
        path: ./resume.pdf

  deploy-from-linux-build:
    needs: [build-linux, build-resume-linux]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Download artifacts
      uses: actions/download-artifact@v4

    - name: Prepare for GitHub Pages deployment
      run: |
        mkdir -p gh-pages
        cp -r web-build-gh-pages/* gh-pages/
        mkdir -p gh-pages/files
        cp -r resume-ubuntu/resume.pdf gh-pages/files/resume.pdf

    - name: Deploy to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: gh-pages

  deploy-from-macos-build:
    needs: [build-macos, build-resume-macos]
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Download artifacts
      uses: actions/download-artifact@v4

    - name: Prepare for GitHub Pages deployment (macOS)
      run: |
        mkdir -p gh-pages-mac
        cp -r web-build-gh-pages/* gh-pages-mac/
        mkdir -p gh-pages-mac/files
        cp -r resume-macos/resume.pdf gh-pages-mac/files/resume.pdf

    - name: Deploy to gh-pages-mac branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages-mac
        folder: gh-pages-mac

