name: Build and deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  build-and-deploy:

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ['14.x']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and build web app
      run: |
        cp spa-github-pages/index.html public/index.html
        yarn install
        yarn run build
        cp spa-github-pages/404.html build/

    - name: Generate resume source files
      run: yarn run build:resume

    - name: Compile Resume PDF
      uses: xu-cheng/latex-action@v3
      with:
        root_file: resume/resume.tex
        latexmk_use_xelatex: true

    - name: Prepare deployment folder
      run: |
        mkdir -p build/files/resume
        cp resume/resume.pdf build/files/resume/resume.pdf

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build

